/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\cmd\redux\reduxblender\city2.glb -o C:\cmd\redux\reduxblender\city2.jsx --shadows --keepnames --printwidth 120 --precision 3 --transform --resolution 1024 --keepmeshes --keepmaterials --format webp 
Files: C:\cmd\redux\reduxblender\city2.glb [4.13KB] > C:\cmd\redux\reduxblender\city2-transformed.glb [1.98KB] (52%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function city2(props) {
  const { nodes, materials } = useGLTF('/city2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Plane_1" castShadow receiveShadow geometry={nodes.Plane_1.geometry} material={materials.pColor1} />
      <mesh name="Plane_2" castShadow receiveShadow geometry={nodes.Plane_2.geometry} material={materials.pColor2} />
    </group>
  )
}

useGLTF.preload('/city2-transformed.glb')
