/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\cmd\redux\reduxblender\poster1.glb -o C:\cmd\redux\reduxblender\poster1.jsx --shadows --keepnames --printwidth 120 --precision 3 --transform --resolution 1024 --keepmeshes --keepmaterials --format webp 
Files: C:\cmd\redux\reduxblender\poster1.glb [19.99MB] > C:\cmd\redux\reduxblender\poster1.glb [258.42KB] (99%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function poster1(props) {
  const { nodes, materials } = useGLTF('/poster1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Cube001"
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.piso}
        position={[-1.387, 3.37, -8.739]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[18.333, 1, 40.333]}
      />
      <mesh
        name="Plane005"
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials.piso}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        name="C-组件#2"
        castShadow
        receiveShadow
        geometry={nodes['C-组件#2'].geometry}
        material={materials.Material}
      />
      <mesh
        name="C-组件#2_1"
        castShadow
        receiveShadow
        geometry={nodes['C-组件#2_1'].geometry}
        material={materials.图片1}
      />
      <mesh
        name="C-组件#2_2"
        castShadow
        receiveShadow
        geometry={nodes['C-组件#2_2'].geometry}
        material={materials['5d15cb048d0317f5849b0330226d100f']}
      />
      <mesh
        name="C-组件#2_3"
        castShadow
        receiveShadow
        geometry={nodes['C-组件#2_3'].geometry}
        material={materials['<auto>3']}
      />
      <mesh
        name="C-组件#2_4"
        castShadow
        receiveShadow
        geometry={nodes['C-组件#2_4'].geometry}
        material={materials['4592bcf78c1471705314e665ecea0efb']}
      />
    </group>
  )
}

useGLTF.preload('/poster1.glb')
