/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\3D\Track\ddm_gt6_syracus\redux\syr2.glb -o D:\3D\Track\ddm_gt6_syracus\redux\syr2.jsx --shadows --keepnames --printwidth 120 --precision 3 --transform --resolution 2048 --keepmeshes --keepmaterials --format webp --instance --instanceall 
Files: D:\3D\Track\ddm_gt6_syracus\redux\syr2.glb [152.18MB] > D:\3D\Track\ddm_gt6_syracus\redux\showroom.glb [12.73MB] (92%)
*/

import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = React.createContext()

export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/showroom.glb')
  const instances = React.useMemo(
    () => ({
      ROADrd: nodes['1ROAD_rd'],
      ROADrd1: nodes['1ROAD_rd2'],
      ROADsm: nodes['1ROAD_sm26'],
      A: nodes.a,
      B: nodes.b,
      Object: nodes.Object001,
      Sm: nodes.sm_0,
      Sm1: nodes.sm_1,
      Sm2: nodes.sm_2,
      Sm3: nodes.sm_3,
      Sm4: nodes.sm_4,
      Sm5: nodes.sm_5,
      Sm6: nodes.sm_6,
      Sm7: nodes.sm_7,
      Sm8: nodes.sm_8,
      Sm9: nodes.sm_9,
      Sm10: nodes.sm_10,
      Sm11: nodes.sm_11,
      Sm12: nodes.sm_12,
      Sm13: nodes.sm_13,
      Sm14: nodes.sm_14,
      Sm15: nodes.sm_15,
      Sm16: nodes.sm_16,
      Sm17: nodes.sm_17,
      Sm18: nodes.sm_18,
      Sm19: nodes.sm_19,
      Sm20: nodes.sm_20,
      Sm21: nodes.sm_21,
      Sm22: nodes.sm_22,
      Sm23: nodes.sm_23,
      Sm24: nodes.sm_24,
      Sm25: nodes.sm_25,
      Sm26: nodes.sm_27,
      Sm27: nodes.sm_29,
      Sm28: nodes.sm_30,
      Sm29: nodes.sm_31,
      Sm30: nodes.sm_34,
      Sm31: nodes.sm_35,
      Sm32: nodes.sm_36,
      Sm33: nodes.sm_37,
      Sm34: nodes.sm_38,
      Sm35: nodes.sm_39,
      Sm36: nodes.sm_41,
      Sm37: nodes.sm_42,
      Sm38: nodes.sm_43,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function syr2(props) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.ROADrd name="1ROAD_rd" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.ROADrd1
        name="1ROAD_rd2"
        position={[-54.137, 4.506, -3.375]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <instances.ROADsm
        name="1ROAD_sm26"
        position={[-54.137, 4.506, -3.375]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <instances.A name="a" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.B name="b" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Object name="Object001" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm name="sm_0" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm1 name="sm_1" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm2 name="sm_2" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm3 name="sm_3" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm4 name="sm_4" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm5 name="sm_5" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm6 name="sm_6" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm7 name="sm_7" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm8 name="sm_8" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm9 name="sm_9" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm10 name="sm_10" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm11 name="sm_11" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm12 name="sm_12" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm13 name="sm_13" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm14 name="sm_14" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm15 name="sm_15" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm16 name="sm_16" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm17 name="sm_17" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm18 name="sm_18" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm19 name="sm_19" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm20 name="sm_20" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm21 name="sm_21" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm22 name="sm_22" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm23 name="sm_23" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm24 name="sm_24" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm25 name="sm_25" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm26 name="sm_27" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm27 name="sm_29" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm28 name="sm_30" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm29 name="sm_31" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm30 name="sm_34" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm31 name="sm_35" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm32 name="sm_36" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm33 name="sm_37" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm34 name="sm_38" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm35 name="sm_39" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm36 name="sm_41" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm37 name="sm_42" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <instances.Sm38 name="sm_43" position={[-54.137, 4.506, -3.375]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/showroom.glb')
