/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\3D\Vehicle\Cars\Raw\Ferrari\new\blender\gltfjsx\test3.glb -o D:\3D\Vehicle\Cars\Raw\Ferrari\new\blender\gltfjsx\test3.jsx --shadows --keepnames --printwidth 120 --precision 3 --transform --resolution 1024 --format webp 
Files: D:\3D\Vehicle\Cars\Raw\Ferrari\new\blender\gltfjsx\test3.glb [10.14MB] > D:\3D\Vehicle\Cars\Raw\Ferrari\new\blender\gltfjsx\test3-transformed.glb [705.41KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function test3(props) {
  const { nodes, materials } = useGLTF('/test3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        name="6126effa-49e1-4cda-aab3-5c7b4463f4c2002"
        castShadow
        receiveShadow
        geometry={nodes['6126effa-49e1-4cda-aab3-5c7b4463f4c2002'].geometry}
        material={materials.ext_chassis}
        position={[-1.394, 0.217, 0]}
        rotation={[1.561, 0.01, -3.141]}
        scale={-0.1}
      />
      <mesh
        name="0bc85326-f470-4043-9386-4633b07a81c0001"
        castShadow
        receiveShadow
        geometry={nodes['0bc85326-f470-4043-9386-4633b07a81c0001'].geometry}
        material={materials.ext_livery_1}
        position={[-1.394, 0.208, 0]}
        rotation={[-Math.PI / 2, -0.01, 0]}
      />
      <mesh
        name="32cf26f4-2142-4371-85ad-835ead0186fe001"
        castShadow
        receiveShadow
        geometry={nodes['32cf26f4-2142-4371-85ad-835ead0186fe001'].geometry}
        material={materials.ext_livery_2}
        position={[-1.394, 0.208, 0]}
        rotation={[-Math.PI / 2, -0.01, 0]}
      />
    </group>
  )
}

useGLTF.preload('/test3-transformed.glb')
