/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\3D\Fredini\cars\models\f152m_sp\CSR2\Export\gts.glb -o D:\3D\Fredini\cars\models\f152m_sp\CSR2\Export\gts.jsx --types --shadows --keepnames --meta --printwidth 120 --precision 3 --transform --resolution 1024 --keepmeshes --keepmaterials --format png 
Files: D:\3D\Fredini\cars\models\f152m_sp\CSR2\Export\gts.glb [9.83MB] > D:\3D\Fredini\cars\models\f152m_sp\CSR2\Export\gts-transformed.glb [1.77MB] (82%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'All Animations'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    HoodEngine_Hood_Piston_1: THREE.Mesh
    HoodEngine_Hood_Piston_2: THREE.Mesh
    HoodColoured_Hood: THREE.Mesh
    HoodEngine_Hood: THREE.Mesh
    HoodGrille5_Hood: THREE.Mesh
    HoodPaint_Hood: THREE.Mesh
    HoodEngine_Hood_Rod_1: THREE.Mesh
    HoodEngine_Hood_Rod_2: THREE.Mesh
    CaliperLF_Calliper_Front_L_1: THREE.Mesh
    CaliperLF_Calliper_Front_L_2: THREE.Mesh
    CaliperLF_Calliper_Front_L_3: THREE.Mesh
    CaliperLR_Calliper_Rear_L_1: THREE.Mesh
    CaliperLR_Calliper_Rear_L_2: THREE.Mesh
    CaliperLR_Calliper_Rear_L_3: THREE.Mesh
    CaliperRF_Calliper_Front_R_1: THREE.Mesh
    CaliperRF_Calliper_Front_R_2: THREE.Mesh
    CaliperRF_Calliper_Front_R_3: THREE.Mesh
    CaliperRR_Calliper_Rear_R_1: THREE.Mesh
    CaliperRR_Calliper_Rear_R_2: THREE.Mesh
    CaliperRR_Calliper_Rear_R_3: THREE.Mesh
    Wheel1A_LF_Wheel_Front_L: THREE.Mesh
    Wheel1A_LR_Wheel_Rear_L: THREE.Mesh
    Wheel1A_RF_Wheel_Front_R: THREE.Mesh
    Wheel1A_RR_Wheel_Rear_R: THREE.Mesh
    BrakePedalColoured_Body: THREE.Mesh
    BrakePedalEngine_Body: THREE.Mesh
    ChassisBadge_Body: THREE.Mesh
    ChassisBase_Body: THREE.Mesh
    ChassisColoured_Body: THREE.Mesh
    ChassisEngine_Body: THREE.Mesh
    ChassisGlass_Body_1: THREE.Mesh
    ChassisGlass_Body_2: THREE.Mesh
    ChassisGlassInside_Body: THREE.Mesh
    ChassisGrille1_Body: THREE.Mesh
    ChassisGrille2_Body: THREE.Mesh
    ChassisGrille3_Body: THREE.Mesh
    ChassisGrille4_Body: THREE.Mesh
    ChassisGrille5_Body: THREE.Mesh
    ChassisGrille6_Body: THREE.Mesh
    ChassisInterior_Body_1: THREE.Mesh
    ChassisInterior_Body_2: THREE.Mesh
    ChassisInteriorTilling_Body: THREE.Mesh
    ChassisLight_Body: THREE.Mesh
    ChassisPaint_Body: THREE.Mesh
    DriverSeatBeltColoured_Body: THREE.Mesh
    DriverSeatColoured_Body: THREE.Mesh
    DriverSeatInterior_Body_1: THREE.Mesh
    DriverSeatInterior_Body_2: THREE.Mesh
    DriverSeatInteriorTillingColourZone_Body: THREE.Mesh
    DoorLBase_Door_FrontLeft: THREE.Mesh
    DoorLColoured_Door_FrontLeft: THREE.Mesh
    DoorLGrille1_Door_FrontLeft: THREE.Mesh
    DoorLInterior_Door_FrontLeft_1: THREE.Mesh
    DoorLInterior_Door_FrontLeft_2: THREE.Mesh
    DoorLInteriorTilling_Door_FrontLeft: THREE.Mesh
    DoorLPaint_Door_FrontLeft: THREE.Mesh
    DoorLGlass_DoorWindow_FrontLeft: THREE.Mesh
    DoorLGlassInside_DoorWindow_FrontLeft: THREE.Mesh
    DoorLColoured_Door_FrontLeft_Hinge_1: THREE.Mesh
    DoorRBase_Door_FrontRight: THREE.Mesh
    DoorRColoured_Door_FrontRight: THREE.Mesh
    DoorRGrille1_Door_FrontRight: THREE.Mesh
    DoorRInterior_Door_FrontRight_1: THREE.Mesh
    DoorRInterior_Door_FrontRight_2: THREE.Mesh
    DoorRInteriorTilling_Door_FrontRight: THREE.Mesh
    DoorRPaint_Door_FrontRight: THREE.Mesh
    DoorRGlass_DoorWindow_FrontRight: THREE.Mesh
    DoorRGlassInside_DoorWindow_FrontRight: THREE.Mesh
    DoorRColoured_Door_FrontRight_Hinge_1: THREE.Mesh
    RearWindowGlass_Rear_Window: THREE.Mesh
    RearWindowGlassInside_Rear_Window: THREE.Mesh
    RoofColoured_Roof_Hinge_11: THREE.Mesh
    RoofInterior_Roof_Hinge_11: THREE.Mesh
    RoofPaint_Roof_Hinge_11: THREE.Mesh
    RoofColoured_Roof_Piston_1: THREE.Mesh
    RoofColoured_Roof_Hinge_4: THREE.Mesh
    RoofColoured_Roof_Hinge_3: THREE.Mesh
    RoofColoured_Roof_Hinge_5: THREE.Mesh
    RoofInterior_Roof_Hinge_5: THREE.Mesh
    RoofPaint_Roof_Hinge_5: THREE.Mesh
    RoofBase_Roof: THREE.Mesh
    RoofInterior_Roof: THREE.Mesh
    RoofPaint_Roof: THREE.Mesh
    RoofEngine_Roof_Hinge_7: THREE.Mesh
    RoofEngine_Roof_Hinge_6: THREE.Mesh
    RoofInterior_Roof_Hinge_1: THREE.Mesh
    RoofPaint_Roof_Hinge_1: THREE.Mesh
    RoofEngine_Roof_Hinge_8: THREE.Mesh
    RoofEngine_Roof_Hinge_2: THREE.Mesh
    RoofInterior_Roof_Hinge_2: THREE.Mesh
    RoofPaint_Roof_Hinge_2: THREE.Mesh
    RoofEngine_Roof_Piston_2: THREE.Mesh
    RoofEngine_Roof_Hinge_10: THREE.Mesh
    RoofEngine_Roof_Hinge_9: THREE.Mesh
    RoofEngine_Roof_Rod_1: THREE.Mesh
    RoofEngine_Roof_Rod_2: THREE.Mesh
    SteeringWheelGrille7_SteeringWheel: THREE.Mesh
    SteeringWheelInterior_SteeringWheel_1: THREE.Mesh
    SteeringWheelInterior_SteeringWheel_2: THREE.Mesh
    SteeringWheelInteriorTilling_SteeringWheel: THREE.Mesh
    TrunkColoured_Trunk_Rotate: THREE.Mesh
    TrunkEngine_Trunk_Rod_1: THREE.Mesh
    TrunkEngine_Trunk_Rod_2: THREE.Mesh
    TrunkBadge_Trunk: THREE.Mesh
    TrunkColoured_Trunk: THREE.Mesh
    TrunkGlass_Trunk_1: THREE.Mesh
    TrunkGlass_Trunk_2: THREE.Mesh
    TrunkLight_Trunk: THREE.Mesh
    TrunkPaint_Trunk: THREE.Mesh
    TrunkEngine_Trunk_Piston_1: THREE.Mesh
    TrunkEngine_Trunk_Piston_2: THREE.Mesh
    GasPedalColoured_Body: THREE.Mesh
    GasPedalEngine_Body: THREE.Mesh
    LicensePlate_Body: THREE.Mesh
    ManufacturerPlate_Body: THREE.Mesh
    PaddleShifterInterior_Body: THREE.Mesh
    PassengerSeatBeltColoured_Body: THREE.Mesh
    PassengerSeatColoured_Body: THREE.Mesh
    PassengerSeatInterior_Body_1: THREE.Mesh
    PassengerSeatInterior_Body_2: THREE.Mesh
    PassengerSeatInteriorTillingColourZone_Body: THREE.Mesh
  }
  materials: {
    EngineA: THREE.MeshStandardMaterial
    Coloured: THREE.MeshStandardMaterial
    Grille5A: THREE.MeshStandardMaterial
    Paint: THREE.MeshStandardMaterial
    CaliperGloss: THREE.MeshStandardMaterial
    CaliperGlossPaint: THREE.MeshStandardMaterial
    CaliperBadgeA: THREE.MeshStandardMaterial
    Wheel1A: THREE.MeshStandardMaterial
    BadgeA: THREE.MeshStandardMaterial
    Base: THREE.MeshStandardMaterial
    GlassMtl: THREE.MeshStandardMaterial
    GlassRed: THREE.MeshStandardMaterial
    Grille1A: THREE.MeshStandardMaterial
    Grille2A: THREE.MeshStandardMaterial
    Grille3A: THREE.MeshStandardMaterial
    Grille4A: THREE.MeshStandardMaterial
    Grille6A: THREE.MeshStandardMaterial
    InteriorA: THREE.MeshStandardMaterial
    InteriorColour1A: THREE.MeshStandardMaterial
    InteriorTillingA: THREE.MeshStandardMaterial
    LightA: THREE.MeshStandardMaterial
    InteriorTillingColourZoneA: THREE.MeshStandardMaterial
    Grille7A: THREE.MeshStandardMaterial
    LicensePlateDefaultA: THREE.MeshStandardMaterial
    ManufacturerPlateA: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function gts(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/gts-transformed.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Empty_Animate_Body"
          position={[0, 0.088, 0]}
          rotation={[1.578, 0, 0]}
          userData={{ name: 'Empty_Animate_Body' }}>
          <group name="Empty_Animate_Hood" position={[0, 0.477, -0.748]} userData={{ name: 'Empty_Animate_Hood' }}>
            <group
              name="Empty_Animate_Hood_Piston_1"
              position={[0.753, 0.24, 0.039]}
              rotation={[-0.308, -0.012, 0.036]}
              userData={{ name: 'Empty_Animate_Hood_Piston_1' }}>
              <mesh
                name="HoodEngine_Hood_Piston_1"
                castShadow
                receiveShadow
                geometry={nodes.HoodEngine_Hood_Piston_1.geometry}
                material={materials.EngineA}
                position={[-0.78, -0.897, 0.55]}
                rotation={[-1.269, 0.038, 0]}
                userData={{ name: 'HoodEngine_Hood_Piston_1' }}
              />
            </group>
            <group
              name="Empty_Animate_Hood_Piston_2"
              position={[-0.753, 0.24, 0.039]}
              rotation={[-0.308, 0.012, -0.036]}
              userData={{ name: 'Empty_Animate_Hood_Piston_2' }}>
              <mesh
                name="HoodEngine_Hood_Piston_2"
                castShadow
                receiveShadow
                geometry={nodes.HoodEngine_Hood_Piston_2.geometry}
                material={materials.EngineA}
                position={[0.78, -0.897, 0.55]}
                rotation={[-1.269, -0.038, 0]}
                userData={{ name: 'HoodEngine_Hood_Piston_2' }}
              />
            </group>
            <mesh
              name="HoodColoured_Hood"
              castShadow
              receiveShadow
              geometry={nodes.HoodColoured_Hood.geometry}
              material={materials.Coloured}
              position={[0, -0.477, 0.836]}
              rotation={[-1.578, 0, 0]}
              userData={{ name: 'HoodColoured_Hood' }}
            />
            <mesh
              name="HoodEngine_Hood"
              castShadow
              receiveShadow
              geometry={nodes.HoodEngine_Hood.geometry}
              material={materials.EngineA}
              position={[0, -0.477, 0.836]}
              rotation={[-1.578, 0, 0]}
              userData={{ name: 'HoodEngine_Hood' }}
            />
            <mesh
              name="HoodGrille5_Hood"
              castShadow
              receiveShadow
              geometry={nodes.HoodGrille5_Hood.geometry}
              material={materials.Grille5A}
              position={[0, -0.477, 0.836]}
              rotation={[-1.578, 0, 0]}
              userData={{ name: 'HoodGrille5_Hood' }}
            />
            <mesh
              name="HoodPaint_Hood"
              castShadow
              receiveShadow
              geometry={nodes.HoodPaint_Hood.geometry}
              material={materials.Paint}
              position={[0, -0.477, 0.836]}
              rotation={[-1.578, 0, 0]}
              userData={{ name: 'HoodPaint_Hood' }}
            />
          </group>
          <group
            name="Empty_Animate_Hood_Rod_1"
            position={[0.757, 0.613, -0.675]}
            rotation={[-0.308, -0.012, 0.036]}
            userData={{ name: 'Empty_Animate_Hood_Rod_1' }}>
            <mesh
              name="HoodEngine_Hood_Rod_1"
              castShadow
              receiveShadow
              geometry={nodes.HoodEngine_Hood_Rod_1.geometry}
              material={materials.EngineA}
              position={[-0.78, -0.787, 0.55]}
              rotation={[-1.269, 0.038, 0]}
              userData={{ name: 'HoodEngine_Hood_Rod_1' }}
            />
          </group>
          <group
            name="Empty_Animate_Hood_Rod_2"
            position={[-0.757, 0.613, -0.675]}
            rotation={[-0.308, 0.012, -0.036]}
            userData={{ name: 'Empty_Animate_Hood_Rod_2' }}>
            <mesh
              name="HoodEngine_Hood_Rod_2"
              castShadow
              receiveShadow
              geometry={nodes.HoodEngine_Hood_Rod_2.geometry}
              material={materials.EngineA}
              position={[0.78, -0.787, 0.55]}
              rotation={[-1.269, -0.038, 0]}
              userData={{ name: 'HoodEngine_Hood_Rod_2' }}
            />
          </group>
        </group>
        <group name="CaliperLF_Calliper_Front_L" userData={{ name: 'CaliperLF_Calliper Front L' }}>
          <mesh
            name="CaliperLF_Calliper_Front_L_1"
            castShadow
            receiveShadow
            geometry={nodes.CaliperLF_Calliper_Front_L_1.geometry}
            material={materials.CaliperGloss}
          />
          <mesh
            name="CaliperLF_Calliper_Front_L_2"
            castShadow
            receiveShadow
            geometry={nodes.CaliperLF_Calliper_Front_L_2.geometry}
            material={materials.CaliperGlossPaint}
          />
          <mesh
            name="CaliperLF_Calliper_Front_L_3"
            castShadow
            receiveShadow
            geometry={nodes.CaliperLF_Calliper_Front_L_3.geometry}
            material={materials.CaliperBadgeA}
          />
        </group>
        <group name="CaliperLR_Calliper_Rear_L" userData={{ name: 'CaliperLR_Calliper Rear L' }}>
          <mesh
            name="CaliperLR_Calliper_Rear_L_1"
            castShadow
            receiveShadow
            geometry={nodes.CaliperLR_Calliper_Rear_L_1.geometry}
            material={materials.CaliperGloss}
          />
          <mesh
            name="CaliperLR_Calliper_Rear_L_2"
            castShadow
            receiveShadow
            geometry={nodes.CaliperLR_Calliper_Rear_L_2.geometry}
            material={materials.CaliperGlossPaint}
          />
          <mesh
            name="CaliperLR_Calliper_Rear_L_3"
            castShadow
            receiveShadow
            geometry={nodes.CaliperLR_Calliper_Rear_L_3.geometry}
            material={materials.CaliperBadgeA}
          />
        </group>
        <group name="CaliperRF_Calliper_Front_R" userData={{ name: 'CaliperRF_Calliper Front R' }}>
          <mesh
            name="CaliperRF_Calliper_Front_R_1"
            castShadow
            receiveShadow
            geometry={nodes.CaliperRF_Calliper_Front_R_1.geometry}
            material={materials.CaliperGloss}
          />
          <mesh
            name="CaliperRF_Calliper_Front_R_2"
            castShadow
            receiveShadow
            geometry={nodes.CaliperRF_Calliper_Front_R_2.geometry}
            material={materials.CaliperGlossPaint}
          />
          <mesh
            name="CaliperRF_Calliper_Front_R_3"
            castShadow
            receiveShadow
            geometry={nodes.CaliperRF_Calliper_Front_R_3.geometry}
            material={materials.CaliperBadgeA}
          />
        </group>
        <group name="CaliperRR_Calliper_Rear_R" userData={{ name: 'CaliperRR_Calliper Rear R' }}>
          <mesh
            name="CaliperRR_Calliper_Rear_R_1"
            castShadow
            receiveShadow
            geometry={nodes.CaliperRR_Calliper_Rear_R_1.geometry}
            material={materials.CaliperGloss}
          />
          <mesh
            name="CaliperRR_Calliper_Rear_R_2"
            castShadow
            receiveShadow
            geometry={nodes.CaliperRR_Calliper_Rear_R_2.geometry}
            material={materials.CaliperGlossPaint}
          />
          <mesh
            name="CaliperRR_Calliper_Rear_R_3"
            castShadow
            receiveShadow
            geometry={nodes.CaliperRR_Calliper_Rear_R_3.geometry}
            material={materials.CaliperBadgeA}
          />
        </group>
        <mesh
          name="Wheel1A_LF_Wheel_Front_L"
          castShadow
          receiveShadow
          geometry={nodes.Wheel1A_LF_Wheel_Front_L.geometry}
          material={materials.Wheel1A}
          userData={{ name: 'Wheel1A_LF_Wheel Front L' }}
        />
        <mesh
          name="Wheel1A_LR_Wheel_Rear_L"
          castShadow
          receiveShadow
          geometry={nodes.Wheel1A_LR_Wheel_Rear_L.geometry}
          material={materials.Wheel1A}
          userData={{ name: 'Wheel1A_LR_Wheel Rear L' }}
        />
        <mesh
          name="Wheel1A_RF_Wheel_Front_R"
          castShadow
          receiveShadow
          geometry={nodes.Wheel1A_RF_Wheel_Front_R.geometry}
          material={materials.Wheel1A}
          userData={{ name: 'Wheel1A_RF_Wheel Front R' }}
        />
        <mesh
          name="Wheel1A_RR_Wheel_Rear_R"
          castShadow
          receiveShadow
          geometry={nodes.Wheel1A_RR_Wheel_Rear_R.geometry}
          material={materials.Wheel1A}
          userData={{ name: 'Wheel1A_RR_Wheel Rear R' }}
        />
        <mesh
          name="BrakePedalColoured_Body"
          castShadow
          receiveShadow
          geometry={nodes.BrakePedalColoured_Body.geometry}
          material={materials.Coloured}
          userData={{ name: 'BrakePedalColoured_Body' }}
        />
        <mesh
          name="BrakePedalEngine_Body"
          castShadow
          receiveShadow
          geometry={nodes.BrakePedalEngine_Body.geometry}
          material={materials.EngineA}
          userData={{ name: 'BrakePedalEngine_Body' }}
        />
        <mesh
          name="ChassisBadge_Body"
          castShadow
          receiveShadow
          geometry={nodes.ChassisBadge_Body.geometry}
          material={materials.BadgeA}
          userData={{ name: 'ChassisBadge_Body' }}
        />
        <mesh
          name="ChassisBase_Body"
          castShadow
          receiveShadow
          geometry={nodes.ChassisBase_Body.geometry}
          material={materials.Base}
          userData={{ name: 'ChassisBase_Body' }}
        />
        <mesh
          name="ChassisColoured_Body"
          castShadow
          receiveShadow
          geometry={nodes.ChassisColoured_Body.geometry}
          material={materials.Coloured}
          userData={{ name: 'ChassisColoured_Body' }}
        />
        <mesh
          name="ChassisEngine_Body"
          castShadow
          receiveShadow
          geometry={nodes.ChassisEngine_Body.geometry}
          material={materials.EngineA}
          userData={{ name: 'ChassisEngine_Body' }}
        />
        <group name="ChassisGlass_Body" userData={{ name: 'ChassisGlass_Body' }}>
          <mesh
            name="ChassisGlass_Body_1"
            castShadow
            receiveShadow
            geometry={nodes.ChassisGlass_Body_1.geometry}
            material={materials.GlassMtl}
          />
          <mesh
            name="ChassisGlass_Body_2"
            castShadow
            receiveShadow
            geometry={nodes.ChassisGlass_Body_2.geometry}
            material={materials.GlassRed}
          />
        </group>
        <mesh
          name="ChassisGlassInside_Body"
          castShadow
          receiveShadow
          geometry={nodes.ChassisGlassInside_Body.geometry}
          material={materials.GlassMtl}
          userData={{ name: 'ChassisGlassInside_Body' }}
        />
        <mesh
          name="ChassisGrille1_Body"
          castShadow
          receiveShadow
          geometry={nodes.ChassisGrille1_Body.geometry}
          material={materials.Grille1A}
          userData={{ name: 'ChassisGrille1_Body' }}
        />
        <mesh
          name="ChassisGrille2_Body"
          castShadow
          receiveShadow
          geometry={nodes.ChassisGrille2_Body.geometry}
          material={materials.Grille2A}
          userData={{ name: 'ChassisGrille2_Body' }}
        />
        <mesh
          name="ChassisGrille3_Body"
          castShadow
          receiveShadow
          geometry={nodes.ChassisGrille3_Body.geometry}
          material={materials.Grille3A}
          userData={{ name: 'ChassisGrille3_Body' }}
        />
        <mesh
          name="ChassisGrille4_Body"
          castShadow
          receiveShadow
          geometry={nodes.ChassisGrille4_Body.geometry}
          material={materials.Grille4A}
          userData={{ name: 'ChassisGrille4_Body' }}
        />
        <mesh
          name="ChassisGrille5_Body"
          castShadow
          receiveShadow
          geometry={nodes.ChassisGrille5_Body.geometry}
          material={materials.Grille5A}
          userData={{ name: 'ChassisGrille5_Body' }}
        />
        <mesh
          name="ChassisGrille6_Body"
          castShadow
          receiveShadow
          geometry={nodes.ChassisGrille6_Body.geometry}
          material={materials.Grille6A}
          userData={{ name: 'ChassisGrille6_Body' }}
        />
        <group name="ChassisInterior_Body" userData={{ name: 'ChassisInterior_Body' }}>
          <mesh
            name="ChassisInterior_Body_1"
            castShadow
            receiveShadow
            geometry={nodes.ChassisInterior_Body_1.geometry}
            material={materials.InteriorA}
          />
          <mesh
            name="ChassisInterior_Body_2"
            castShadow
            receiveShadow
            geometry={nodes.ChassisInterior_Body_2.geometry}
            material={materials.InteriorColour1A}
          />
        </group>
        <mesh
          name="ChassisInteriorTilling_Body"
          castShadow
          receiveShadow
          geometry={nodes.ChassisInteriorTilling_Body.geometry}
          material={materials.InteriorTillingA}
          userData={{ name: 'ChassisInteriorTilling_Body' }}
        />
        <mesh
          name="ChassisLight_Body"
          castShadow
          receiveShadow
          geometry={nodes.ChassisLight_Body.geometry}
          material={materials.LightA}
          userData={{ name: 'ChassisLight_Body' }}
        />
        <mesh
          name="ChassisPaint_Body"
          castShadow
          receiveShadow
          geometry={nodes.ChassisPaint_Body.geometry}
          material={materials.Paint}
          userData={{ name: 'ChassisPaint_Body' }}
        />
        <mesh
          name="DriverSeatBeltColoured_Body"
          castShadow
          receiveShadow
          geometry={nodes.DriverSeatBeltColoured_Body.geometry}
          material={materials.Coloured}
          userData={{ name: 'DriverSeatBeltColoured_Body' }}
        />
        <mesh
          name="DriverSeatColoured_Body"
          castShadow
          receiveShadow
          geometry={nodes.DriverSeatColoured_Body.geometry}
          material={materials.Coloured}
          userData={{ name: 'DriverSeatColoured_Body' }}
        />
        <group name="DriverSeatInterior_Body" userData={{ name: 'DriverSeatInterior_Body' }}>
          <mesh
            name="DriverSeatInterior_Body_1"
            castShadow
            receiveShadow
            geometry={nodes.DriverSeatInterior_Body_1.geometry}
            material={materials.InteriorA}
          />
          <mesh
            name="DriverSeatInterior_Body_2"
            castShadow
            receiveShadow
            geometry={nodes.DriverSeatInterior_Body_2.geometry}
            material={materials.InteriorColour1A}
          />
        </group>
        <mesh
          name="DriverSeatInteriorTillingColourZone_Body"
          castShadow
          receiveShadow
          geometry={nodes.DriverSeatInteriorTillingColourZone_Body.geometry}
          material={materials.InteriorTillingColourZoneA}
          userData={{ name: 'DriverSeatInteriorTillingColourZone_Body' }}
        />
        <mesh
          name="DoorLBase_Door_FrontLeft"
          castShadow
          receiveShadow
          geometry={nodes.DoorLBase_Door_FrontLeft.geometry}
          material={materials.Base}
          userData={{ name: 'DoorLBase_Door_FrontLeft' }}
        />
        <mesh
          name="DoorLColoured_Door_FrontLeft"
          castShadow
          receiveShadow
          geometry={nodes.DoorLColoured_Door_FrontLeft.geometry}
          material={materials.Coloured}
          userData={{ name: 'DoorLColoured_Door_FrontLeft' }}
        />
        <mesh
          name="DoorLGrille1_Door_FrontLeft"
          castShadow
          receiveShadow
          geometry={nodes.DoorLGrille1_Door_FrontLeft.geometry}
          material={materials.Grille1A}
          userData={{ name: 'DoorLGrille1_Door_FrontLeft' }}
        />
        <group name="DoorLInterior_Door_FrontLeft" userData={{ name: 'DoorLInterior_Door_FrontLeft' }}>
          <mesh
            name="DoorLInterior_Door_FrontLeft_1"
            castShadow
            receiveShadow
            geometry={nodes.DoorLInterior_Door_FrontLeft_1.geometry}
            material={materials.InteriorA}
          />
          <mesh
            name="DoorLInterior_Door_FrontLeft_2"
            castShadow
            receiveShadow
            geometry={nodes.DoorLInterior_Door_FrontLeft_2.geometry}
            material={materials.InteriorColour1A}
          />
        </group>
        <mesh
          name="DoorLInteriorTilling_Door_FrontLeft"
          castShadow
          receiveShadow
          geometry={nodes.DoorLInteriorTilling_Door_FrontLeft.geometry}
          material={materials.InteriorTillingA}
          userData={{ name: 'DoorLInteriorTilling_Door_FrontLeft' }}
        />
        <mesh
          name="DoorLPaint_Door_FrontLeft"
          castShadow
          receiveShadow
          geometry={nodes.DoorLPaint_Door_FrontLeft.geometry}
          material={materials.Paint}
          userData={{ name: 'DoorLPaint_Door_FrontLeft' }}
        />
        <mesh
          name="DoorLGlass_DoorWindow_FrontLeft"
          castShadow
          receiveShadow
          geometry={nodes.DoorLGlass_DoorWindow_FrontLeft.geometry}
          material={materials.GlassMtl}
          userData={{ name: 'DoorLGlass_DoorWindow_FrontLeft' }}
        />
        <mesh
          name="DoorLGlassInside_DoorWindow_FrontLeft"
          castShadow
          receiveShadow
          geometry={nodes.DoorLGlassInside_DoorWindow_FrontLeft.geometry}
          material={materials.GlassMtl}
          userData={{ name: 'DoorLGlassInside_DoorWindow_FrontLeft' }}
        />
        <mesh
          name="DoorLColoured_Door_FrontLeft_Hinge_1"
          castShadow
          receiveShadow
          geometry={nodes.DoorLColoured_Door_FrontLeft_Hinge_1.geometry}
          material={materials.Coloured}
          userData={{ name: 'DoorLColoured_Door_FrontLeft_Hinge_1' }}
        />
        <mesh
          name="DoorRBase_Door_FrontRight"
          castShadow
          receiveShadow
          geometry={nodes.DoorRBase_Door_FrontRight.geometry}
          material={materials.Base}
          userData={{ name: 'DoorRBase_Door_FrontRight' }}
        />
        <mesh
          name="DoorRColoured_Door_FrontRight"
          castShadow
          receiveShadow
          geometry={nodes.DoorRColoured_Door_FrontRight.geometry}
          material={materials.Coloured}
          userData={{ name: 'DoorRColoured_Door_FrontRight' }}
        />
        <mesh
          name="DoorRGrille1_Door_FrontRight"
          castShadow
          receiveShadow
          geometry={nodes.DoorRGrille1_Door_FrontRight.geometry}
          material={materials.Grille1A}
          userData={{ name: 'DoorRGrille1_Door_FrontRight' }}
        />
        <group name="DoorRInterior_Door_FrontRight" userData={{ name: 'DoorRInterior_Door_FrontRight' }}>
          <mesh
            name="DoorRInterior_Door_FrontRight_1"
            castShadow
            receiveShadow
            geometry={nodes.DoorRInterior_Door_FrontRight_1.geometry}
            material={materials.InteriorA}
          />
          <mesh
            name="DoorRInterior_Door_FrontRight_2"
            castShadow
            receiveShadow
            geometry={nodes.DoorRInterior_Door_FrontRight_2.geometry}
            material={materials.InteriorColour1A}
          />
        </group>
        <mesh
          name="DoorRInteriorTilling_Door_FrontRight"
          castShadow
          receiveShadow
          geometry={nodes.DoorRInteriorTilling_Door_FrontRight.geometry}
          material={materials.InteriorTillingA}
          userData={{ name: 'DoorRInteriorTilling_Door_FrontRight' }}
        />
        <mesh
          name="DoorRPaint_Door_FrontRight"
          castShadow
          receiveShadow
          geometry={nodes.DoorRPaint_Door_FrontRight.geometry}
          material={materials.Paint}
          userData={{ name: 'DoorRPaint_Door_FrontRight' }}
        />
        <mesh
          name="DoorRGlass_DoorWindow_FrontRight"
          castShadow
          receiveShadow
          geometry={nodes.DoorRGlass_DoorWindow_FrontRight.geometry}
          material={materials.GlassMtl}
          userData={{ name: 'DoorRGlass_DoorWindow_FrontRight' }}
        />
        <mesh
          name="DoorRGlassInside_DoorWindow_FrontRight"
          castShadow
          receiveShadow
          geometry={nodes.DoorRGlassInside_DoorWindow_FrontRight.geometry}
          material={materials.GlassMtl}
          userData={{ name: 'DoorRGlassInside_DoorWindow_FrontRight' }}
        />
        <mesh
          name="DoorRColoured_Door_FrontRight_Hinge_1"
          castShadow
          receiveShadow
          geometry={nodes.DoorRColoured_Door_FrontRight_Hinge_1.geometry}
          material={materials.Coloured}
          userData={{ name: 'DoorRColoured_Door_FrontRight_Hinge_1' }}
        />
        <mesh
          name="RearWindowGlass_Rear_Window"
          castShadow
          receiveShadow
          geometry={nodes.RearWindowGlass_Rear_Window.geometry}
          material={materials.GlassMtl}
          userData={{ name: 'RearWindowGlass_Rear_Window' }}
        />
        <mesh
          name="RearWindowGlassInside_Rear_Window"
          castShadow
          receiveShadow
          geometry={nodes.RearWindowGlassInside_Rear_Window.geometry}
          material={materials.GlassMtl}
          userData={{ name: 'RearWindowGlassInside_Rear_Window' }}
        />
        <mesh
          name="RoofColoured_Roof_Hinge_11"
          castShadow
          receiveShadow
          geometry={nodes.RoofColoured_Roof_Hinge_11.geometry}
          material={materials.Coloured}
          userData={{ name: 'RoofColoured_Roof_Hinge_11' }}
        />
        <mesh
          name="RoofInterior_Roof_Hinge_11"
          castShadow
          receiveShadow
          geometry={nodes.RoofInterior_Roof_Hinge_11.geometry}
          material={materials.InteriorA}
          userData={{ name: 'RoofInterior_Roof_Hinge_11' }}
        />
        <mesh
          name="RoofPaint_Roof_Hinge_11"
          castShadow
          receiveShadow
          geometry={nodes.RoofPaint_Roof_Hinge_11.geometry}
          material={materials.Paint}
          userData={{ name: 'RoofPaint_Roof_Hinge_11' }}
        />
        <mesh
          name="RoofColoured_Roof_Piston_1"
          castShadow
          receiveShadow
          geometry={nodes.RoofColoured_Roof_Piston_1.geometry}
          material={materials.Coloured}
          userData={{ name: 'RoofColoured_Roof_Piston_1' }}
        />
        <mesh
          name="RoofColoured_Roof_Hinge_4"
          castShadow
          receiveShadow
          geometry={nodes.RoofColoured_Roof_Hinge_4.geometry}
          material={materials.Coloured}
          userData={{ name: 'RoofColoured_Roof_Hinge_4' }}
        />
        <mesh
          name="RoofColoured_Roof_Hinge_3"
          castShadow
          receiveShadow
          geometry={nodes.RoofColoured_Roof_Hinge_3.geometry}
          material={materials.Coloured}
          userData={{ name: 'RoofColoured_Roof_Hinge_3' }}
        />
        <mesh
          name="RoofColoured_Roof_Hinge_5"
          castShadow
          receiveShadow
          geometry={nodes.RoofColoured_Roof_Hinge_5.geometry}
          material={materials.Coloured}
          userData={{ name: 'RoofColoured_Roof_Hinge_5' }}
        />
        <mesh
          name="RoofInterior_Roof_Hinge_5"
          castShadow
          receiveShadow
          geometry={nodes.RoofInterior_Roof_Hinge_5.geometry}
          material={materials.InteriorA}
          userData={{ name: 'RoofInterior_Roof_Hinge_5' }}
        />
        <mesh
          name="RoofPaint_Roof_Hinge_5"
          castShadow
          receiveShadow
          geometry={nodes.RoofPaint_Roof_Hinge_5.geometry}
          material={materials.Paint}
          userData={{ name: 'RoofPaint_Roof_Hinge_5' }}
        />
        <mesh
          name="RoofBase_Roof"
          castShadow
          receiveShadow
          geometry={nodes.RoofBase_Roof.geometry}
          material={materials.Base}
          userData={{ name: 'RoofBase_Roof' }}
        />
        <mesh
          name="RoofInterior_Roof"
          castShadow
          receiveShadow
          geometry={nodes.RoofInterior_Roof.geometry}
          material={materials.InteriorA}
          userData={{ name: 'RoofInterior_Roof' }}
        />
        <mesh
          name="RoofPaint_Roof"
          castShadow
          receiveShadow
          geometry={nodes.RoofPaint_Roof.geometry}
          material={materials.Paint}
          userData={{ name: 'RoofPaint_Roof' }}
        />
        <mesh
          name="RoofEngine_Roof_Hinge_7"
          castShadow
          receiveShadow
          geometry={nodes.RoofEngine_Roof_Hinge_7.geometry}
          material={materials.EngineA}
          userData={{ name: 'RoofEngine_Roof_Hinge_7' }}
        />
        <mesh
          name="RoofEngine_Roof_Hinge_6"
          castShadow
          receiveShadow
          geometry={nodes.RoofEngine_Roof_Hinge_6.geometry}
          material={materials.EngineA}
          userData={{ name: 'RoofEngine_Roof_Hinge_6' }}
        />
        <mesh
          name="RoofInterior_Roof_Hinge_1"
          castShadow
          receiveShadow
          geometry={nodes.RoofInterior_Roof_Hinge_1.geometry}
          material={materials.InteriorA}
          userData={{ name: 'RoofInterior_Roof_Hinge_1' }}
        />
        <mesh
          name="RoofPaint_Roof_Hinge_1"
          castShadow
          receiveShadow
          geometry={nodes.RoofPaint_Roof_Hinge_1.geometry}
          material={materials.Paint}
          userData={{ name: 'RoofPaint_Roof_Hinge_1' }}
        />
        <mesh
          name="RoofEngine_Roof_Hinge_8"
          castShadow
          receiveShadow
          geometry={nodes.RoofEngine_Roof_Hinge_8.geometry}
          material={materials.EngineA}
          userData={{ name: 'RoofEngine_Roof_Hinge_8' }}
        />
        <mesh
          name="RoofEngine_Roof_Hinge_2"
          castShadow
          receiveShadow
          geometry={nodes.RoofEngine_Roof_Hinge_2.geometry}
          material={materials.EngineA}
          userData={{ name: 'RoofEngine_Roof_Hinge_2' }}
        />
        <mesh
          name="RoofInterior_Roof_Hinge_2"
          castShadow
          receiveShadow
          geometry={nodes.RoofInterior_Roof_Hinge_2.geometry}
          material={materials.InteriorA}
          userData={{ name: 'RoofInterior_Roof_Hinge_2' }}
        />
        <mesh
          name="RoofPaint_Roof_Hinge_2"
          castShadow
          receiveShadow
          geometry={nodes.RoofPaint_Roof_Hinge_2.geometry}
          material={materials.Paint}
          userData={{ name: 'RoofPaint_Roof_Hinge_2' }}
        />
        <mesh
          name="RoofEngine_Roof_Piston_2"
          castShadow
          receiveShadow
          geometry={nodes.RoofEngine_Roof_Piston_2.geometry}
          material={materials.EngineA}
          userData={{ name: 'RoofEngine_Roof_Piston_2' }}
        />
        <mesh
          name="RoofEngine_Roof_Hinge_10"
          castShadow
          receiveShadow
          geometry={nodes.RoofEngine_Roof_Hinge_10.geometry}
          material={materials.EngineA}
          userData={{ name: 'RoofEngine_Roof_Hinge_10' }}
        />
        <mesh
          name="RoofEngine_Roof_Hinge_9"
          castShadow
          receiveShadow
          geometry={nodes.RoofEngine_Roof_Hinge_9.geometry}
          material={materials.EngineA}
          userData={{ name: 'RoofEngine_Roof_Hinge_9' }}
        />
        <mesh
          name="RoofEngine_Roof_Rod_1"
          castShadow
          receiveShadow
          geometry={nodes.RoofEngine_Roof_Rod_1.geometry}
          material={materials.EngineA}
          userData={{ name: 'RoofEngine_Roof_Rod_1' }}
        />
        <mesh
          name="RoofEngine_Roof_Rod_2"
          castShadow
          receiveShadow
          geometry={nodes.RoofEngine_Roof_Rod_2.geometry}
          material={materials.EngineA}
          userData={{ name: 'RoofEngine_Roof_Rod_2' }}
        />
        <mesh
          name="SteeringWheelGrille7_SteeringWheel"
          castShadow
          receiveShadow
          geometry={nodes.SteeringWheelGrille7_SteeringWheel.geometry}
          material={materials.Grille7A}
          userData={{ name: 'SteeringWheelGrille7_SteeringWheel' }}
        />
        <group name="SteeringWheelInterior_SteeringWheel" userData={{ name: 'SteeringWheelInterior_SteeringWheel' }}>
          <mesh
            name="SteeringWheelInterior_SteeringWheel_1"
            castShadow
            receiveShadow
            geometry={nodes.SteeringWheelInterior_SteeringWheel_1.geometry}
            material={materials.InteriorA}
          />
          <mesh
            name="SteeringWheelInterior_SteeringWheel_2"
            castShadow
            receiveShadow
            geometry={nodes.SteeringWheelInterior_SteeringWheel_2.geometry}
            material={materials.InteriorColour1A}
          />
        </group>
        <mesh
          name="SteeringWheelInteriorTilling_SteeringWheel"
          castShadow
          receiveShadow
          geometry={nodes.SteeringWheelInteriorTilling_SteeringWheel.geometry}
          material={materials.InteriorTillingA}
          userData={{ name: 'SteeringWheelInteriorTilling_SteeringWheel' }}
        />
        <mesh
          name="TrunkColoured_Trunk_Rotate"
          castShadow
          receiveShadow
          geometry={nodes.TrunkColoured_Trunk_Rotate.geometry}
          material={materials.Coloured}
          userData={{ name: 'TrunkColoured_Trunk_Rotate' }}
        />
        <mesh
          name="TrunkEngine_Trunk_Rod_1"
          castShadow
          receiveShadow
          geometry={nodes.TrunkEngine_Trunk_Rod_1.geometry}
          material={materials.EngineA}
          userData={{ name: 'TrunkEngine_Trunk_Rod_1' }}
        />
        <mesh
          name="TrunkEngine_Trunk_Rod_2"
          castShadow
          receiveShadow
          geometry={nodes.TrunkEngine_Trunk_Rod_2.geometry}
          material={materials.EngineA}
          userData={{ name: 'TrunkEngine_Trunk_Rod_2' }}
        />
        <mesh
          name="TrunkBadge_Trunk"
          castShadow
          receiveShadow
          geometry={nodes.TrunkBadge_Trunk.geometry}
          material={materials.BadgeA}
          userData={{ name: 'TrunkBadge_Trunk' }}
        />
        <mesh
          name="TrunkColoured_Trunk"
          castShadow
          receiveShadow
          geometry={nodes.TrunkColoured_Trunk.geometry}
          material={materials.Coloured}
          userData={{ name: 'TrunkColoured_Trunk' }}
        />
        <group name="TrunkGlass_Trunk" userData={{ name: 'TrunkGlass_Trunk' }}>
          <mesh
            name="TrunkGlass_Trunk_1"
            castShadow
            receiveShadow
            geometry={nodes.TrunkGlass_Trunk_1.geometry}
            material={materials.GlassMtl}
          />
          <mesh
            name="TrunkGlass_Trunk_2"
            castShadow
            receiveShadow
            geometry={nodes.TrunkGlass_Trunk_2.geometry}
            material={materials.GlassRed}
          />
        </group>
        <mesh
          name="TrunkLight_Trunk"
          castShadow
          receiveShadow
          geometry={nodes.TrunkLight_Trunk.geometry}
          material={materials.LightA}
          userData={{ name: 'TrunkLight_Trunk' }}
        />
        <mesh
          name="TrunkPaint_Trunk"
          castShadow
          receiveShadow
          geometry={nodes.TrunkPaint_Trunk.geometry}
          material={materials.Paint}
          userData={{ name: 'TrunkPaint_Trunk' }}
        />
        <mesh
          name="TrunkEngine_Trunk_Piston_1"
          castShadow
          receiveShadow
          geometry={nodes.TrunkEngine_Trunk_Piston_1.geometry}
          material={materials.EngineA}
          userData={{ name: 'TrunkEngine_Trunk_Piston_1' }}
        />
        <mesh
          name="TrunkEngine_Trunk_Piston_2"
          castShadow
          receiveShadow
          geometry={nodes.TrunkEngine_Trunk_Piston_2.geometry}
          material={materials.EngineA}
          userData={{ name: 'TrunkEngine_Trunk_Piston_2' }}
        />
        <mesh
          name="GasPedalColoured_Body"
          castShadow
          receiveShadow
          geometry={nodes.GasPedalColoured_Body.geometry}
          material={materials.Coloured}
          userData={{ name: 'GasPedalColoured_Body' }}
        />
        <mesh
          name="GasPedalEngine_Body"
          castShadow
          receiveShadow
          geometry={nodes.GasPedalEngine_Body.geometry}
          material={materials.EngineA}
          userData={{ name: 'GasPedalEngine_Body' }}
        />
        <mesh
          name="LicensePlate_Body"
          castShadow
          receiveShadow
          geometry={nodes.LicensePlate_Body.geometry}
          material={materials.LicensePlateDefaultA}
          userData={{ name: 'LicensePlate_Body' }}
        />
        <mesh
          name="ManufacturerPlate_Body"
          castShadow
          receiveShadow
          geometry={nodes.ManufacturerPlate_Body.geometry}
          material={materials.ManufacturerPlateA}
          userData={{ name: 'ManufacturerPlate_Body' }}
        />
        <mesh
          name="PaddleShifterInterior_Body"
          castShadow
          receiveShadow
          geometry={nodes.PaddleShifterInterior_Body.geometry}
          material={materials.InteriorA}
          userData={{ name: 'PaddleShifterInterior_Body' }}
        />
        <mesh
          name="PassengerSeatBeltColoured_Body"
          castShadow
          receiveShadow
          geometry={nodes.PassengerSeatBeltColoured_Body.geometry}
          material={materials.Coloured}
          userData={{ name: 'PassengerSeatBeltColoured_Body' }}
        />
        <mesh
          name="PassengerSeatColoured_Body"
          castShadow
          receiveShadow
          geometry={nodes.PassengerSeatColoured_Body.geometry}
          material={materials.Coloured}
          userData={{ name: 'PassengerSeatColoured_Body' }}
        />
        <group name="PassengerSeatInterior_Body" userData={{ name: 'PassengerSeatInterior_Body' }}>
          <mesh
            name="PassengerSeatInterior_Body_1"
            castShadow
            receiveShadow
            geometry={nodes.PassengerSeatInterior_Body_1.geometry}
            material={materials.InteriorA}
          />
          <mesh
            name="PassengerSeatInterior_Body_2"
            castShadow
            receiveShadow
            geometry={nodes.PassengerSeatInterior_Body_2.geometry}
            material={materials.InteriorColour1A}
          />
        </group>
        <mesh
          name="PassengerSeatInteriorTillingColourZone_Body"
          castShadow
          receiveShadow
          geometry={nodes.PassengerSeatInteriorTillingColourZone_Body.geometry}
          material={materials.InteriorTillingColourZoneA}
          userData={{ name: 'PassengerSeatInteriorTillingColourZone_Body' }}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/gts-transformed.glb')
