/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\3D\Vehicle\Cars\AC\asw-f1-2025-ferrari-sf-25\ferrari_sf25\New Folder\sf25.glb -o D:\3D\Vehicle\Cars\AC\asw-f1-2025-ferrari-sf-25\ferrari_sf25\New Folder\sf25.jsx --types --shadows --keepnames --meta --printwidth 120 --precision 3 --transform --resolution 4096 --keepmeshes --keepmaterials --format png 
Files: D:\3D\Vehicle\Cars\AC\asw-f1-2025-ferrari-sf-25\ferrari_sf25\New Folder\sf25.glb [36.83MB] > D:\3D\Vehicle\Cars\AC\asw-f1-2025-ferrari-sf-25\ferrari_sf25\New Folder\sf25-transformed.glb [20.3MB] (45%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    cockpit: THREE.Mesh
    cockpit002: THREE.Mesh
    cockpit003: THREE.Mesh
    cockpit_chrome001: THREE.Mesh
    cockpit_chrome002: THREE.Mesh
    cockpit_legs_support: THREE.Mesh
    exhaust: THREE.Mesh
    HALO_PAINT001: THREE.Mesh
    LCD: THREE.Mesh
    LCD_GLASS: THREE.Mesh
    LED: THREE.Mesh
    LED_back: THREE.Mesh
    LEDs: THREE.Mesh
    MIRRORL: THREE.Mesh
    MIRRORR: THREE.Mesh
    Rain_Lights: THREE.Mesh
    Rain_Lights2: THREE.Mesh
    ['SF-25']: THREE.Mesh
    ['SF-25002']: THREE.Mesh
    ['SF-25003']: THREE.Mesh
    ['SF-25004']: THREE.Mesh
    ['SF-25005']: THREE.Mesh
    ['SF-25006']: THREE.Mesh
    ['SF-25007']: THREE.Mesh
    ['SF-25008']: THREE.Mesh
    ['SF-25009']: THREE.Mesh
    ['SF-2501']: THREE.Mesh
    ['SF-25010']: THREE.Mesh
    ['SF-25011']: THREE.Mesh
    ['SF-25012']: THREE.Mesh
    ['SF-25013']: THREE.Mesh
    ['SF-25014']: THREE.Mesh
    ['SF-25015']: THREE.Mesh
    ['SF-25016']: THREE.Mesh
    ['SF-25017']: THREE.Mesh
    ['SF-25018']: THREE.Mesh
    ['SF-25019']: THREE.Mesh
    ['SF-25020']: THREE.Mesh
    ['SF-25021']: THREE.Mesh
    ['SF-25022']: THREE.Mesh
    ['SF-25023']: THREE.Mesh
    ['SF-25024']: THREE.Mesh
    ['SF-25025']: THREE.Mesh
    ['SF-25026']: THREE.Mesh
    ['SF-25027']: THREE.Mesh
    ['SF-25028']: THREE.Mesh
    ['SF-25029']: THREE.Mesh
    ['SF-25030']: THREE.Mesh
    ['SF-25031']: THREE.Mesh
    ['SF-25032']: THREE.Mesh
    ['SF-25033']: THREE.Mesh
    ['SF-25034']: THREE.Mesh
    ['SF-25035']: THREE.Mesh
    ['SF-25036']: THREE.Mesh
    ['SF-25037']: THREE.Mesh
    ['SF-25038']: THREE.Mesh
    ['SF-25039']: THREE.Mesh
    ['SF-25040']: THREE.Mesh
    ['SF-25041']: THREE.Mesh
    ['SF-25042']: THREE.Mesh
    ['SF-25043']: THREE.Mesh
    ['SF-2507']: THREE.Mesh
    ['SF-25081']: THREE.Mesh
    ['SF-251017']: THREE.Mesh
    ['SF-25154']: THREE.Mesh
    ['SF-25205']: THREE.Mesh
    ['SF-25235']: THREE.Mesh
    ['SF-25268']: THREE.Mesh
    ['SF-25365']: THREE.Mesh
    ['SF-25463']: THREE.Mesh
    ['SF-25582']: THREE.Mesh
    ['SF-25586']: THREE.Mesh
    ['SF-25589']: THREE.Mesh
    ['SF-25687']: THREE.Mesh
    ['SF-25690']: THREE.Mesh
    ['SF-25691']: THREE.Mesh
    ['SF-25734']: THREE.Mesh
    ['SF-25768']: THREE.Mesh
    ['SF-25797']: THREE.Mesh
    ['SF-25804']: THREE.Mesh
    ['SF-25813']: THREE.Mesh
    ['SF-25831']: THREE.Mesh
    ['SF-25851']: THREE.Mesh
    ['SF-25857']: THREE.Mesh
    ['SF-25882']: THREE.Mesh
    ['SF-25923']: THREE.Mesh
    ['SF-25943']: THREE.Mesh
    ['SF-25957']: THREE.Mesh
    ['SF-25960']: THREE.Mesh
    ['SF-25962']: THREE.Mesh
    ['SF-25987']: THREE.Mesh
    ['SF-25994']: THREE.Mesh
    ['SF-25c3']: THREE.Mesh
    ['SF-25_c1']: THREE.Mesh
    ['SF-25_c2']: THREE.Mesh
    ['SF-25_fw_l']: THREE.Mesh
    ['SF-25_fw_r']: THREE.Mesh
    SW_BODY: THREE.Mesh
    SW_DECALS: THREE.Mesh
    SW_DECALS_2: THREE.Mesh
    SW_DETAILS: THREE.Mesh
    SW_HANDLES: THREE.Mesh
    SW_METAL: THREE.Mesh
    SW_PLASTIC: THREE.Mesh
    TYRE_LF_SUB0: THREE.Mesh
    TYRE_LF_SUB1: THREE.Mesh
    TYRE_LR_SUB0: THREE.Mesh
    TYRE_LR_SUB1: THREE.Mesh
    TYRE_RF_SUB0: THREE.Mesh
    TYRE_RF_SUB1: THREE.Mesh
    TYRE_RR_SUB0: THREE.Mesh
    TYRE_RR_SUB1: THREE.Mesh
    wheel_bl: THREE.Mesh
    wheel_br: THREE.Mesh
    wheel_fl: THREE.Mesh
    wheel_fr: THREE.Mesh
  }
  materials: {
    generics: THREE.MeshStandardMaterial
    cockpit_carbon: THREE.MeshStandardMaterial
    ferrari_carbon1: THREE.MeshStandardMaterial
    cockpit_metal: THREE.MeshStandardMaterial
    cockpit_foam: THREE.MeshStandardMaterial
    exhaust: THREE.MeshStandardMaterial
    carbon_halo: THREE.MeshStandardMaterial
    LCD: THREE.MeshStandardMaterial
    LCD_GLASS: THREE.MeshStandardMaterial
    indicator_lights: THREE.MeshStandardMaterial
    indicator_lights_back: THREE.MeshStandardMaterial
    SW_LEDS: THREE.MeshStandardMaterial
    Mirror: THREE.MeshStandardMaterial
    Rear_Light: THREE.MeshStandardMaterial
    Decal_3: THREE.MeshStandardMaterial
    Paint_2: THREE.MeshStandardMaterial
    Carbon_2: THREE.MeshStandardMaterial
    Decal_1: THREE.MeshStandardMaterial
    Decal_2: THREE.MeshStandardMaterial
    Detail: THREE.MeshStandardMaterial
    Generic: THREE.MeshStandardMaterial
    HP: THREE.MeshStandardMaterial
    ferrari_number_16: THREE.MeshStandardMaterial
    Carbon_1: THREE.MeshStandardMaterial
    Paint_1: THREE.MeshStandardMaterial
    ferrari_number_rear: THREE.MeshStandardMaterial
    Decal_4: THREE.MeshStandardMaterial
    TCAM: THREE.MeshStandardMaterial
    SW_CARBON: THREE.MeshStandardMaterial
    ferrari_decal: THREE.MeshStandardMaterial
    SW_DECALS: THREE.MeshStandardMaterial
    SW_HANDLES: THREE.MeshStandardMaterial
    SW_METAL: THREE.MeshStandardMaterial
    SW_PLASTIC: THREE.MeshStandardMaterial
    TIRE_SIDES: THREE.MeshStandardMaterial
    TIRE_TREAD: THREE.MeshStandardMaterial
    ferrari_wheel_hub: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function sf25(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/sf25-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="cockpit"
        castShadow
        receiveShadow
        geometry={nodes.cockpit.geometry}
        material={materials.generics}
        userData={{ name: 'cockpit' }}
      />
      <mesh
        name="cockpit002"
        castShadow
        receiveShadow
        geometry={nodes.cockpit002.geometry}
        material={materials.cockpit_carbon}
        userData={{ name: 'cockpit.002' }}
      />
      <mesh
        name="cockpit003"
        castShadow
        receiveShadow
        geometry={nodes.cockpit003.geometry}
        material={materials.ferrari_carbon1}
        userData={{ name: 'cockpit.003' }}
      />
      <mesh
        name="cockpit_chrome001"
        castShadow
        receiveShadow
        geometry={nodes.cockpit_chrome001.geometry}
        material={materials.cockpit_metal}
        userData={{ name: 'cockpit_chrome001' }}
      />
      <mesh
        name="cockpit_chrome002"
        castShadow
        receiveShadow
        geometry={nodes.cockpit_chrome002.geometry}
        material={materials.cockpit_metal}
        userData={{ name: 'cockpit_chrome002' }}
      />
      <mesh
        name="cockpit_legs_support"
        castShadow
        receiveShadow
        geometry={nodes.cockpit_legs_support.geometry}
        material={materials.cockpit_foam}
        userData={{ name: 'cockpit_legs_support' }}
      />
      <mesh
        name="exhaust"
        castShadow
        receiveShadow
        geometry={nodes.exhaust.geometry}
        material={materials.exhaust}
        userData={{ name: 'exhaust' }}
      />
      <mesh
        name="HALO_PAINT001"
        castShadow
        receiveShadow
        geometry={nodes.HALO_PAINT001.geometry}
        material={materials.carbon_halo}
        userData={{ name: 'HALO_PAINT.001' }}
      />
      <mesh
        name="LCD"
        castShadow
        receiveShadow
        geometry={nodes.LCD.geometry}
        material={materials.LCD}
        userData={{ name: 'LCD' }}
      />
      <mesh
        name="LCD_GLASS"
        castShadow
        receiveShadow
        geometry={nodes.LCD_GLASS.geometry}
        material={materials.LCD_GLASS}
        userData={{ name: 'LCD_GLASS' }}
      />
      <mesh
        name="LED"
        castShadow
        receiveShadow
        geometry={nodes.LED.geometry}
        material={materials.indicator_lights}
        userData={{ name: 'LED' }}
      />
      <mesh
        name="LED_back"
        castShadow
        receiveShadow
        geometry={nodes.LED_back.geometry}
        material={materials.indicator_lights_back}
        userData={{ name: 'LED_back' }}
      />
      <mesh
        name="LEDs"
        castShadow
        receiveShadow
        geometry={nodes.LEDs.geometry}
        material={materials.SW_LEDS}
        userData={{ name: 'LEDs' }}
      />
      <mesh
        name="MIRRORL"
        castShadow
        receiveShadow
        geometry={nodes.MIRRORL.geometry}
        material={materials.Mirror}
        userData={{ name: 'MIRRORL' }}
      />
      <mesh
        name="MIRRORR"
        castShadow
        receiveShadow
        geometry={nodes.MIRRORR.geometry}
        material={materials.Mirror}
        userData={{ name: 'MIRRORR' }}
      />
      <mesh
        name="Rain_Lights"
        castShadow
        receiveShadow
        geometry={nodes.Rain_Lights.geometry}
        material={materials.Rear_Light}
        userData={{ name: 'Rain_Lights' }}
      />
      <mesh
        name="Rain_Lights2"
        castShadow
        receiveShadow
        geometry={nodes.Rain_Lights2.geometry}
        material={materials.Rear_Light}
        userData={{ name: 'Rain_Lights2' }}
      />
      <mesh
        name="SF-25"
        castShadow
        receiveShadow
        geometry={nodes['SF-25'].geometry}
        material={materials.Decal_3}
        userData={{ name: 'SF-25' }}
      />
      <mesh
        name="SF-25002"
        castShadow
        receiveShadow
        geometry={nodes['SF-25002'].geometry}
        material={materials.Paint_2}
        userData={{ name: 'SF-25.002' }}
      />
      <mesh
        name="SF-25003"
        castShadow
        receiveShadow
        geometry={nodes['SF-25003'].geometry}
        material={materials.Carbon_2}
        userData={{ name: 'SF-25.003' }}
      />
      <mesh
        name="SF-25004"
        castShadow
        receiveShadow
        geometry={nodes['SF-25004'].geometry}
        material={materials.Decal_1}
        userData={{ name: 'SF-25.004' }}
      />
      <mesh
        name="SF-25005"
        castShadow
        receiveShadow
        geometry={nodes['SF-25005'].geometry}
        material={materials.Decal_2}
        userData={{ name: 'SF-25.005' }}
      />
      <mesh
        name="SF-25006"
        castShadow
        receiveShadow
        geometry={nodes['SF-25006'].geometry}
        material={materials.Detail}
        userData={{ name: 'SF-25.006' }}
      />
      <mesh
        name="SF-25007"
        castShadow
        receiveShadow
        geometry={nodes['SF-25007'].geometry}
        material={materials.Generic}
        userData={{ name: 'SF-25.007' }}
      />
      <mesh
        name="SF-25008"
        castShadow
        receiveShadow
        geometry={nodes['SF-25008'].geometry}
        material={materials.HP}
        userData={{ name: 'SF-25.008' }}
      />
      <mesh
        name="SF-25009"
        castShadow
        receiveShadow
        geometry={nodes['SF-25009'].geometry}
        material={materials.ferrari_number_16}
        userData={{ name: 'SF-25.009' }}
      />
      <mesh
        name="SF-2501"
        castShadow
        receiveShadow
        geometry={nodes['SF-2501'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.01' }}
      />
      <mesh
        name="SF-25010"
        castShadow
        receiveShadow
        geometry={nodes['SF-25010'].geometry}
        material={materials.Paint_1}
        userData={{ name: 'SF-25.010' }}
      />
      <mesh
        name="SF-25011"
        castShadow
        receiveShadow
        geometry={nodes['SF-25011'].geometry}
        material={materials.Paint_2}
        userData={{ name: 'SF-25.011' }}
      />
      <mesh
        name="SF-25012"
        castShadow
        receiveShadow
        geometry={nodes['SF-25012'].geometry}
        material={materials.Rear_Light}
        userData={{ name: 'SF-25.012' }}
      />
      <mesh
        name="SF-25013"
        castShadow
        receiveShadow
        geometry={nodes['SF-25013'].geometry}
        material={materials.Detail}
        userData={{ name: 'SF-25.013' }}
      />
      <mesh
        name="SF-25014"
        castShadow
        receiveShadow
        geometry={nodes['SF-25014'].geometry}
        material={materials.carbon_halo}
        userData={{ name: 'SF-25.014' }}
      />
      <mesh
        name="SF-25015"
        castShadow
        receiveShadow
        geometry={nodes['SF-25015'].geometry}
        material={materials.ferrari_number_rear}
        userData={{ name: 'SF-25.015' }}
      />
      <mesh
        name="SF-25016"
        castShadow
        receiveShadow
        geometry={nodes['SF-25016'].geometry}
        material={materials.Detail}
        userData={{ name: 'SF-25.016' }}
      />
      <mesh
        name="SF-25017"
        castShadow
        receiveShadow
        geometry={nodes['SF-25017'].geometry}
        material={materials.Paint_1}
        userData={{ name: 'SF-25.017' }}
      />
      <mesh
        name="SF-25018"
        castShadow
        receiveShadow
        geometry={nodes['SF-25018'].geometry}
        material={materials.Detail}
        userData={{ name: 'SF-25.018' }}
      />
      <mesh
        name="SF-25019"
        castShadow
        receiveShadow
        geometry={nodes['SF-25019'].geometry}
        material={materials.Detail}
        userData={{ name: 'SF-25.019' }}
      />
      <mesh
        name="SF-25020"
        castShadow
        receiveShadow
        geometry={nodes['SF-25020'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.020' }}
      />
      <mesh
        name="SF-25021"
        castShadow
        receiveShadow
        geometry={nodes['SF-25021'].geometry}
        material={materials.Detail}
        userData={{ name: 'SF-25.021' }}
      />
      <mesh
        name="SF-25022"
        castShadow
        receiveShadow
        geometry={nodes['SF-25022'].geometry}
        material={materials.Decal_1}
        userData={{ name: 'SF-25.022' }}
      />
      <mesh
        name="SF-25023"
        castShadow
        receiveShadow
        geometry={nodes['SF-25023'].geometry}
        material={materials.Decal_1}
        userData={{ name: 'SF-25.023' }}
      />
      <mesh
        name="SF-25024"
        castShadow
        receiveShadow
        geometry={nodes['SF-25024'].geometry}
        material={materials.Decal_3}
        userData={{ name: 'SF-25.024' }}
      />
      <mesh
        name="SF-25025"
        castShadow
        receiveShadow
        geometry={nodes['SF-25025'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.025' }}
      />
      <mesh
        name="SF-25026"
        castShadow
        receiveShadow
        geometry={nodes['SF-25026'].geometry}
        material={materials.Decal_3}
        userData={{ name: 'SF-25.026' }}
      />
      <mesh
        name="SF-25027"
        castShadow
        receiveShadow
        geometry={nodes['SF-25027'].geometry}
        material={materials.Decal_4}
        userData={{ name: 'SF-25.027' }}
      />
      <mesh
        name="SF-25028"
        castShadow
        receiveShadow
        geometry={nodes['SF-25028'].geometry}
        material={materials.TCAM}
        userData={{ name: 'SF-25.028' }}
      />
      <mesh
        name="SF-25029"
        castShadow
        receiveShadow
        geometry={nodes['SF-25029'].geometry}
        material={materials.Decal_1}
        userData={{ name: 'SF-25.029' }}
      />
      <mesh
        name="SF-25030"
        castShadow
        receiveShadow
        geometry={nodes['SF-25030'].geometry}
        material={materials.Decal_1}
        userData={{ name: 'SF-25.030' }}
      />
      <mesh
        name="SF-25031"
        castShadow
        receiveShadow
        geometry={nodes['SF-25031'].geometry}
        material={materials.Paint_1}
        userData={{ name: 'SF-25.031' }}
      />
      <mesh
        name="SF-25032"
        castShadow
        receiveShadow
        geometry={nodes['SF-25032'].geometry}
        material={materials.Paint_1}
        userData={{ name: 'SF-25.032' }}
      />
      <mesh
        name="SF-25033"
        castShadow
        receiveShadow
        geometry={nodes['SF-25033'].geometry}
        material={materials.Decal_1}
        userData={{ name: 'SF-25.033' }}
      />
      <mesh
        name="SF-25034"
        castShadow
        receiveShadow
        geometry={nodes['SF-25034'].geometry}
        material={materials.Decal_1}
        userData={{ name: 'SF-25.034' }}
      />
      <mesh
        name="SF-25035"
        castShadow
        receiveShadow
        geometry={nodes['SF-25035'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.035' }}
      />
      <mesh
        name="SF-25036"
        castShadow
        receiveShadow
        geometry={nodes['SF-25036'].geometry}
        material={materials.Decal_3}
        userData={{ name: 'SF-25.036' }}
      />
      <mesh
        name="SF-25037"
        castShadow
        receiveShadow
        geometry={nodes['SF-25037'].geometry}
        material={materials.Detail}
        userData={{ name: 'SF-25.037' }}
      />
      <mesh
        name="SF-25038"
        castShadow
        receiveShadow
        geometry={nodes['SF-25038'].geometry}
        material={materials.Detail}
        userData={{ name: 'SF-25.038' }}
      />
      <mesh
        name="SF-25039"
        castShadow
        receiveShadow
        geometry={nodes['SF-25039'].geometry}
        material={materials.Decal_2}
        userData={{ name: 'SF-25.039' }}
      />
      <mesh
        name="SF-25040"
        castShadow
        receiveShadow
        geometry={nodes['SF-25040'].geometry}
        material={materials.Decal_2}
        userData={{ name: 'SF-25.040' }}
      />
      <mesh
        name="SF-25041"
        castShadow
        receiveShadow
        geometry={nodes['SF-25041'].geometry}
        material={materials.Detail}
        userData={{ name: 'SF-25.041' }}
      />
      <mesh
        name="SF-25042"
        castShadow
        receiveShadow
        geometry={nodes['SF-25042'].geometry}
        material={materials.Decal_3}
        userData={{ name: 'SF-25.042' }}
      />
      <mesh
        name="SF-25043"
        castShadow
        receiveShadow
        geometry={nodes['SF-25043'].geometry}
        material={materials.Decal_3}
        userData={{ name: 'SF-25.043' }}
      />
      <mesh
        name="SF-2507"
        castShadow
        receiveShadow
        geometry={nodes['SF-2507'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.07' }}
      />
      <mesh
        name="SF-25081"
        castShadow
        receiveShadow
        geometry={nodes['SF-25081'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.081' }}
      />
      <mesh
        name="SF-251017"
        castShadow
        receiveShadow
        geometry={nodes['SF-251017'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.1017' }}
      />
      <mesh
        name="SF-25154"
        castShadow
        receiveShadow
        geometry={nodes['SF-25154'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.154' }}
      />
      <mesh
        name="SF-25205"
        castShadow
        receiveShadow
        geometry={nodes['SF-25205'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.205' }}
      />
      <mesh
        name="SF-25235"
        castShadow
        receiveShadow
        geometry={nodes['SF-25235'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.235' }}
      />
      <mesh
        name="SF-25268"
        castShadow
        receiveShadow
        geometry={nodes['SF-25268'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.268' }}
      />
      <mesh
        name="SF-25365"
        castShadow
        receiveShadow
        geometry={nodes['SF-25365'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.365' }}
      />
      <mesh
        name="SF-25463"
        castShadow
        receiveShadow
        geometry={nodes['SF-25463'].geometry}
        material={materials.carbon_halo}
        userData={{ name: 'SF-25.463' }}
      />
      <mesh
        name="SF-25582"
        castShadow
        receiveShadow
        geometry={nodes['SF-25582'].geometry}
        material={materials.carbon_halo}
        userData={{ name: 'SF-25.582' }}
      />
      <mesh
        name="SF-25586"
        castShadow
        receiveShadow
        geometry={nodes['SF-25586'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.586' }}
      />
      <mesh
        name="SF-25589"
        castShadow
        receiveShadow
        geometry={nodes['SF-25589'].geometry}
        material={materials.carbon_halo}
        userData={{ name: 'SF-25.589' }}
      />
      <mesh
        name="SF-25687"
        castShadow
        receiveShadow
        geometry={nodes['SF-25687'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.687' }}
      />
      <mesh
        name="SF-25690"
        castShadow
        receiveShadow
        geometry={nodes['SF-25690'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.690' }}
      />
      <mesh
        name="SF-25691"
        castShadow
        receiveShadow
        geometry={nodes['SF-25691'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.691' }}
      />
      <mesh
        name="SF-25734"
        castShadow
        receiveShadow
        geometry={nodes['SF-25734'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.734' }}
      />
      <mesh
        name="SF-25768"
        castShadow
        receiveShadow
        geometry={nodes['SF-25768'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.768' }}
      />
      <mesh
        name="SF-25797"
        castShadow
        receiveShadow
        geometry={nodes['SF-25797'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.797' }}
      />
      <mesh
        name="SF-25804"
        castShadow
        receiveShadow
        geometry={nodes['SF-25804'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.804' }}
      />
      <mesh
        name="SF-25813"
        castShadow
        receiveShadow
        geometry={nodes['SF-25813'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.813' }}
      />
      <mesh
        name="SF-25831"
        castShadow
        receiveShadow
        geometry={nodes['SF-25831'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.831' }}
      />
      <mesh
        name="SF-25851"
        castShadow
        receiveShadow
        geometry={nodes['SF-25851'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.851' }}
      />
      <mesh
        name="SF-25857"
        castShadow
        receiveShadow
        geometry={nodes['SF-25857'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.857' }}
      />
      <mesh
        name="SF-25882"
        castShadow
        receiveShadow
        geometry={nodes['SF-25882'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.882' }}
      />
      <mesh
        name="SF-25923"
        castShadow
        receiveShadow
        geometry={nodes['SF-25923'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.923' }}
      />
      <mesh
        name="SF-25943"
        castShadow
        receiveShadow
        geometry={nodes['SF-25943'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.943' }}
      />
      <mesh
        name="SF-25957"
        castShadow
        receiveShadow
        geometry={nodes['SF-25957'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.957' }}
      />
      <mesh
        name="SF-25960"
        castShadow
        receiveShadow
        geometry={nodes['SF-25960'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.960' }}
      />
      <mesh
        name="SF-25962"
        castShadow
        receiveShadow
        geometry={nodes['SF-25962'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.962' }}
      />
      <mesh
        name="SF-25987"
        castShadow
        receiveShadow
        geometry={nodes['SF-25987'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.987' }}
      />
      <mesh
        name="SF-25994"
        castShadow
        receiveShadow
        geometry={nodes['SF-25994'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.994' }}
      />
      <mesh
        name="SF-25c3"
        castShadow
        receiveShadow
        geometry={nodes['SF-25c3'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25.c3' }}
      />
      <mesh
        name="SF-25_c1"
        castShadow
        receiveShadow
        geometry={nodes['SF-25_c1'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25_c1' }}
      />
      <mesh
        name="SF-25_c2"
        castShadow
        receiveShadow
        geometry={nodes['SF-25_c2'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25_c2' }}
      />
      <mesh
        name="SF-25_fw_l"
        castShadow
        receiveShadow
        geometry={nodes['SF-25_fw_l'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25_fw_l' }}
      />
      <mesh
        name="SF-25_fw_r"
        castShadow
        receiveShadow
        geometry={nodes['SF-25_fw_r'].geometry}
        material={materials.Carbon_1}
        userData={{ name: 'SF-25_fw_r' }}
      />
      <mesh
        name="SW_BODY"
        castShadow
        receiveShadow
        geometry={nodes.SW_BODY.geometry}
        material={materials.SW_CARBON}
        userData={{ name: 'SW_BODY' }}
      />
      <mesh
        name="SW_DECALS"
        castShadow
        receiveShadow
        geometry={nodes.SW_DECALS.geometry}
        material={materials.ferrari_decal}
        userData={{ name: 'SW_DECALS' }}
      />
      <mesh
        name="SW_DECALS_2"
        castShadow
        receiveShadow
        geometry={nodes.SW_DECALS_2.geometry}
        material={materials.ferrari_number_16}
        userData={{ name: 'SW_DECALS_2' }}
      />
      <mesh
        name="SW_DETAILS"
        castShadow
        receiveShadow
        geometry={nodes.SW_DETAILS.geometry}
        material={materials.SW_DECALS}
        userData={{ name: 'SW_DETAILS' }}
      />
      <mesh
        name="SW_HANDLES"
        castShadow
        receiveShadow
        geometry={nodes.SW_HANDLES.geometry}
        material={materials.SW_HANDLES}
        userData={{ name: 'SW_HANDLES' }}
      />
      <mesh
        name="SW_METAL"
        castShadow
        receiveShadow
        geometry={nodes.SW_METAL.geometry}
        material={materials.SW_METAL}
        userData={{ name: 'SW_METAL' }}
      />
      <mesh
        name="SW_PLASTIC"
        castShadow
        receiveShadow
        geometry={nodes.SW_PLASTIC.geometry}
        material={materials.SW_PLASTIC}
        userData={{ name: 'SW_PLASTIC' }}
      />
      <mesh
        name="TYRE_LF_SUB0"
        castShadow
        receiveShadow
        geometry={nodes.TYRE_LF_SUB0.geometry}
        material={materials.TIRE_SIDES}
        userData={{ name: 'TYRE_LF_SUB0' }}
      />
      <mesh
        name="TYRE_LF_SUB1"
        castShadow
        receiveShadow
        geometry={nodes.TYRE_LF_SUB1.geometry}
        material={materials.TIRE_TREAD}
        userData={{ name: 'TYRE_LF_SUB1' }}
      />
      <mesh
        name="TYRE_LR_SUB0"
        castShadow
        receiveShadow
        geometry={nodes.TYRE_LR_SUB0.geometry}
        material={materials.TIRE_SIDES}
        userData={{ name: 'TYRE_LR_SUB0' }}
      />
      <mesh
        name="TYRE_LR_SUB1"
        castShadow
        receiveShadow
        geometry={nodes.TYRE_LR_SUB1.geometry}
        material={materials.TIRE_TREAD}
        userData={{ name: 'TYRE_LR_SUB1' }}
      />
      <mesh
        name="TYRE_RF_SUB0"
        castShadow
        receiveShadow
        geometry={nodes.TYRE_RF_SUB0.geometry}
        material={materials.TIRE_SIDES}
        userData={{ name: 'TYRE_RF_SUB0' }}
      />
      <mesh
        name="TYRE_RF_SUB1"
        castShadow
        receiveShadow
        geometry={nodes.TYRE_RF_SUB1.geometry}
        material={materials.TIRE_TREAD}
        userData={{ name: 'TYRE_RF_SUB1' }}
      />
      <mesh
        name="TYRE_RR_SUB0"
        castShadow
        receiveShadow
        geometry={nodes.TYRE_RR_SUB0.geometry}
        material={materials.TIRE_SIDES}
        userData={{ name: 'TYRE_RR_SUB0' }}
      />
      <mesh
        name="TYRE_RR_SUB1"
        castShadow
        receiveShadow
        geometry={nodes.TYRE_RR_SUB1.geometry}
        material={materials.TIRE_TREAD}
        userData={{ name: 'TYRE_RR_SUB1' }}
      />
      <mesh
        name="wheel_bl"
        castShadow
        receiveShadow
        geometry={nodes.wheel_bl.geometry}
        material={materials.ferrari_wheel_hub}
        userData={{ name: 'wheel_bl' }}
      />
      <mesh
        name="wheel_br"
        castShadow
        receiveShadow
        geometry={nodes.wheel_br.geometry}
        material={materials.ferrari_wheel_hub}
        userData={{ name: 'wheel_br' }}
      />
      <mesh
        name="wheel_fl"
        castShadow
        receiveShadow
        geometry={nodes.wheel_fl.geometry}
        material={materials.ferrari_wheel_hub}
        userData={{ name: 'wheel_fl' }}
      />
      <mesh
        name="wheel_fr"
        castShadow
        receiveShadow
        geometry={nodes.wheel_fr.geometry}
        material={materials.ferrari_wheel_hub}
        userData={{ name: 'wheel_fr' }}
      />
    </group>
  )
}

useGLTF.preload('/sf25-transformed.glb')
