/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\cmd\redux\reduxblender\car.glb -o C:\cmd\redux\reduxblender\car.jsx --shadows --keepnames --printwidth 120 --precision 3 --transform --resolution 1024 --keepmaterials --format webp 
Files: C:\cmd\redux\reduxblender\car.glb [7.05MB] > C:\cmd\redux\reduxblender\car.glb [1.14MB] (84%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function car(props) {
  const { nodes, materials } = useGLTF('/car.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        name="BrakePedalInterior"
        castShadow
        receiveShadow
        geometry={nodes.BrakePedalInterior.geometry}
        material={materials.interior}
        position={[0, 0.101, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <group name="CaliperLF" position={[-1.379, 0.325, 0.822]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh
          name="Combined3DWheel_3DWheel_front_L_Instance1_Src4002"
          castShadow
          receiveShadow
          geometry={nodes.Combined3DWheel_3DWheel_front_L_Instance1_Src4002.geometry}
          material={materials.CaliperGloss}
        />
        <mesh
          name="Combined3DWheel_3DWheel_front_L_Instance1_Src4002_1"
          castShadow
          receiveShadow
          geometry={nodes.Combined3DWheel_3DWheel_front_L_Instance1_Src4002_1.geometry}
          material={materials.ext_brake_caliper}
        />
        <mesh
          name="Combined3DWheel_3DWheel_front_L_Instance1_Src4002_2"
          castShadow
          receiveShadow
          geometry={nodes.Combined3DWheel_3DWheel_front_L_Instance1_Src4002_2.geometry}
          material={materials.CaliperBadgeA}
        />
      </group>
      <mesh
        name="ChassisBadge"
        castShadow
        receiveShadow
        geometry={nodes.ChassisBadge.geometry}
        material={materials.BadgeA}
        position={[0, 0.101, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="ChassisBase"
        castShadow
        receiveShadow
        geometry={nodes.ChassisBase.geometry}
        material={materials.Base}
        position={[0, 0.101, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="ChassisCarbon1M"
        castShadow
        receiveShadow
        geometry={nodes.ChassisCarbon1M.geometry}
        material={materials.Carbon1M}
        position={[0, 0.101, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="ChassisCarbon2"
        castShadow
        receiveShadow
        geometry={nodes.ChassisCarbon2.geometry}
        material={materials.Carbon2}
        position={[0, 0.101, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="ChassisCarbon2M"
        castShadow
        receiveShadow
        geometry={nodes.ChassisCarbon2M.geometry}
        material={materials.Carbon2M}
        position={[0, 0.101, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <group name="ChassisColoured" position={[0, 0.101, 0]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh
          name="Coloured_Geo_lodA"
          castShadow
          receiveShadow
          geometry={nodes.Coloured_Geo_lodA.geometry}
          material={materials.ext_chrome}
        />
        <mesh
          name="Coloured_Geo_lodA_1"
          castShadow
          receiveShadow
          geometry={nodes.Coloured_Geo_lodA_1.geometry}
          material={materials.Coloured}
        />
      </group>
      <mesh
        name="ChassisEngine"
        castShadow
        receiveShadow
        geometry={nodes.ChassisEngine.geometry}
        material={materials.EngineA}
        position={[0, 0.101, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <group name="ChassisGlass" position={[0, 0.101, 0]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh
          name="Window_Geo_lodA"
          castShadow
          receiveShadow
          geometry={nodes.Window_Geo_lodA.geometry}
          material={materials.glass_windshield}
        />
        <mesh
          name="Window_Geo_lodA_1"
          castShadow
          receiveShadow
          geometry={nodes.Window_Geo_lodA_1.geometry}
          material={materials.glass_taillight}
        />
      </group>
      <mesh
        name="ChassisGrille1"
        castShadow
        receiveShadow
        geometry={nodes.ChassisGrille1.geometry}
        material={materials.Grille1A}
        position={[0, 0.101, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="ChassisGrille2"
        castShadow
        receiveShadow
        geometry={nodes.ChassisGrille2.geometry}
        material={materials.Grille2A}
        position={[0, 0.101, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="ChassisGrille3"
        castShadow
        receiveShadow
        geometry={nodes.ChassisGrille3.geometry}
        material={materials.Grille3A}
        position={[0, 0.101, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="ChassisInterior"
        castShadow
        receiveShadow
        geometry={nodes.ChassisInterior.geometry}
        material={materials.int_color1}
        position={[0, 0.101, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="ChassisLight"
        castShadow
        receiveShadow
        geometry={nodes.ChassisLight.geometry}
        material={materials.LightA}
        position={[0, 0.101, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <group name="ChassisPaint" position={[0, 0.101, 0]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh
          name="Paint_Geo_lodA"
          castShadow
          receiveShadow
          geometry={nodes.Paint_Geo_lodA.geometry}
          material={materials.ext_chassis}
        />
        <mesh
          name="Paint_Geo_lodA_1"
          castShadow
          receiveShadow
          geometry={nodes.Paint_Geo_lodA_1.geometry}
          material={materials.ext_roof}
        />
        <mesh
          name="Paint_Geo_lodA_2"
          castShadow
          receiveShadow
          geometry={nodes.Paint_Geo_lodA_2.geometry}
          material={materials.ext_livery_1}
        />
      </group>
      <mesh
        name="DoorLColoured"
        castShadow
        receiveShadow
        geometry={nodes.DoorLColoured.geometry}
        material={materials.ext_mirror_base}
        position={[0, 0.101, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="DoorLPaint"
        castShadow
        receiveShadow
        geometry={nodes.DoorLPaint.geometry}
        material={materials.ext_mirror_cover}
        position={[0, 0.101, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="DriverSeatInterior"
        castShadow
        receiveShadow
        geometry={nodes.DriverSeatInterior.geometry}
        material={materials.int_color2}
        position={[0, 0.101, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        name="DriverSeatInteriorTillingColourZone"
        castShadow
        receiveShadow
        geometry={nodes.DriverSeatInteriorTillingColourZone.geometry}
        material={materials.int_color3}
        position={[0, 0.101, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <group name="Wheel1A_LF" position={[-1.379, 0.325, 0.822]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh
          name="Combined3DWheel_3DWheel_front_L_Instance1_Src4"
          castShadow
          receiveShadow
          geometry={nodes.Combined3DWheel_3DWheel_front_L_Instance1_Src4.geometry}
          material={materials.Wheel1A}
        />
        <mesh
          name="Combined3DWheel_3DWheel_front_L_Instance1_Src4_1"
          castShadow
          receiveShadow
          geometry={nodes.Combined3DWheel_3DWheel_front_L_Instance1_Src4_1.geometry}
          material={materials.ext_wheel}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/car.glb')
